### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by Kadoshita** [mak0tia/labmatching#6]
https://github.com/mak0tia/labmatching/blob/c45453e1c93492ec02b1e95168fc8712af7d0a68/views/index.ejs#L81

```diff
- 仮装
+ 仮想
```

**Comment by mak0tia** [comment]
ブランチ切るの忘れたので…
https://github.com/mak0tia/labmatching/commit/0d6ddf922cf3f1e68e2f664b46c0addf291367a9
